version: "3"
services:
  bd-dev:
    image: 'postgres:14'
    container_name: 'bd-dev'
    networks:
      - compose-app
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  contacts-app:
    image: contacts-app
    build: ../
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - compose-app
    ports:
      - "8080:8080"
networks:
  compose-app: {}
